### ISSUE TITLE
Adding the Splash Screen 

### ISSUE THREAD

**Issue by Suryansh1720001** [aniketsen123/MVVM_notesapp#14]
Hello @aniketsen123 
I want to add the Splash screen in this application so that the application looks more attractive and the user experience increases.
I want to work on this issue under JWOC. 
Kindly assign this issue to me.
Thank You

**Comment by sarthaknerd** [comment]
hi can you assign this to me for contribution for jwoc

**Comment by avdhendra** [comment]
i can add the splash screen to the your application can you assign me this issue
