### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by tmsagarofficial** [aniketsen123/MVVM_notesapp#18]
I wanted to let u know that i would love to work on this issue to update the 'README.md' with some screenshots of the project and other things which suit the project.

**Comment by aniketsen123** [comment]
ok @tmsagarofficial

**Comment by tmsagarofficial** [comment]
pls check the PR #20

**Comment by tmsagarofficial** [comment]
@aniketsen123 THanks for merging bro 😄
