### ISSUE TITLE
Change the app icon of the application. 

### ISSUE THREAD

**Issue by aniketsen123** [aniketsen123/MVVM_notesapp#2]
Change to the app icon and set a creative one.

**Comment by tmsagarofficial** [comment]
Yes i would love to work on this issue.

**Comment by pjyotianwar** [comment]
Hey @aniketsen123
I want to work on this issue under JWOC

**Comment by tusharsh21** [comment]
I want to work on this issue under JWOC

**Comment by aniketsen123** [comment]
ok @tmsagarofficial

**Comment by utkarsh006** [comment]
I want to work on this issue under JWOC. Kindly assign it to me.
