### ISSUE TITLE
Dark Mode for the app

### ISSUE THREAD

**Issue by sarthaknerd** [aniketsen123/MVVM_notesapp#23]
Dark Mode for the App

**Comment by sarthaknerd** [comment]
@aniketsen123 Please assign this to me and put labels of JWOC , ENHANCEMENT AND HARD

**Comment by aniketsen123** [comment]
ok @sarthaknerd

**Comment by aniketsen123** [comment]
@sarthaknerd please do it fast

**Comment by sarthaknerd** [comment]
i am working on it but due to already present theme it is getting error , can i just comment my code and commit it.

**Comment by aniketsen123** [comment]
yes
