### ISSUE TITLE
Add a Splash Screen.

### ISSUE THREAD

**Issue by aniketsen123** [aniketsen123/MVVM_notesapp#3]
Add a Splash Screen. The Splash Screen will be shown for three seconds before the application starts.

**Comment by aritra-tech** [comment]
Can I do it? @aniketsen123

**Comment by aniketsen123** [comment]
@aritra-tech We are instructed not to assign issues before the contribution period of JWOC begins which is 15th Feb. Also, any comments before that time are not valid. So, wait till then and run the application locally.

**Comment by aritra-tech** [comment]
Okay okay sure

**Comment by pjyotianwar** [comment]
Hey @aniketsen123
I want to work on this issue under JWOC

**Comment by aniketsen123** [comment]
@pjyotianwar sure

**Comment by tusharsh21** [comment]
i want to work on this issue under JWOC
