### ISSUE TITLE
Add a Dialog Box .

### ISSUE THREAD

**Issue by aniketsen123** [aniketsen123/MVVM_notesapp#4]
Before deleting, an existing note, a Alert box will appear, ensuring the user wants to delete the note or not.

**Comment by pjyotianwar** [comment]
Hey @aniketsen123
I want to work on this issue under JWOC

**Comment by tusharsh21** [comment]
I want to work on this issue under JWOC

**Comment by realsh9dy** [comment]
Please assign me this issue

**Comment by aniketsen123** [comment]
ok @realsh9dy

**Comment by sarthaknerd** [comment]
Hi i already fixed this and it running  can you please assign me this
